language: node_js
before_install:
  - npm i -g npm@5
  - npm i -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - NODE_ENV=production npm run build -- -p
after_script:
  - greenkeeper-lockfile-upload
